export const SET_GROUP_VALUE = 'SET_GROUP_VALUE';
export const CLOSE_CLASSIFIERS = 'CLOSE_CLASSIFIERS';
export const OPEN_CLASSIFIERS = 'OPEN_CLASSIFIERS';
export const ONLY_CLOSE = 'ONLY_CLOSE';
export const CLOSE_AND_BACK = 'CLOSE_AND_BACK';
export const CLOSE_HANDLER ='CLOSE_HANDLER';
export const OPEN_HANDLER ='OPEN_HANDLER';