export const GET_ALL_CURRENCY_REQUEST = 'GET_ALL_CURRENCY_REQUEST';
export const GET_ALL_CURRENCY_FAIL = 'GET_ALL_CURRENCY_FAIL';
export const GET_ALL_CURRENCY_SUCCESS = 'GET_ALL_CURRENCY_SUCCESS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const EDIT_CURRENCY = 'EDIT_CURRENCY';
export const SET_VALUES = 'SET_VALUES';
export const SET_FORM_VALIDATE = 'SET_FORM_VALIDATE';