export const GET_ALL_CURRENCY_REQUEST = 'GET_ALL_CURRENCY_REQUEST';
export const GET_ALL_CURRENCY_FAIL = 'GET_ALL_CURRENCY_FAIL';
export const GET_ALL_CURRENCY_SUCCESS = 'GET_ALL_CURRENCY_SUCCESS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const EDIT_CURRENCY = 'EDIT_CURRENCY';
export const SET_VALUES = 'SET_VALUES';
export const SET_FORM_VALIDATE = 'SET_FORM_VALIDATE';


export const GET_ITEM_CURRENCY_REQUEST = 'GET_ITEM_CURRENCY_REQUEST';
export const GET_ITEM_CURRENCY_FAIL = 'GET_ITEM_CURRENCY_FAIL';
export const GET_ITEM_CURRENCY_SUCCESS = 'GET_ITEM_CURRENCY_SUCCESS';

export const FETCH_CURRENCY_REQUEST = 'FETCH_CURRENCY_REQUEST';
export const FETCH_CURRENCY_FAIL = 'FETCH_CURRENCY_FAIL';
export const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS';