export const GET_POSITIONS_REQUEST = "GET_POSITIONS_REQUEST";
export const GET_POSITIONS_FAIL = "GET_POSITIONS_FAIL";
export const GET_POSITIONS_SUCCESS = "GET_POSITIONS_SUCCESS";

export const ADD_MODAL = "ADD_MODAL";
export const EDIT_MODAL = "EDIT_MODAL";
export const DELETE_MODAL = "DELETE_MODAL";
export const SET_MODAL_VALUES = "SET_MODAL_VALUES";

export const HANDLE = "HANDLE";