export const GET_POSITIONS_REQUEST = "GET_POSITIONS_REQUEST";
export const GET_POSITIONS_FAIL = "GET_POSITIONS_FAIL";
export const GET_POSITIONS_SUCCESS = "GET_POSITIONS_SUCCESS";

export const GET_POSITION_REQUEST = "GET_POSITION_REQUEST";
export const GET_POSITION_FAIL = "GET_POSITION_FAIL";
export const GET_POSITION_SUCCESS = "GET_POSITION_SUCCESS";

export const ADD_POSITION_REQUEST = "ADD_POSITION_REQUEST";
export const ADD_POSITION_FAIL = "ADD_POSITION_FAIL";
export const ADD_POSITION_SUCCESS = "ADD_POSITION_SUCCESS";

export const EDIT_POSITION_REQUEST = "EDIT_POSITION_REQUEST";
export const EDIT_POSITION_FAIL = "EDIT_POSITION_FAIL";
export const EDIT_POSITION_SUCCESS = "EDIT_POSITION_SUCCESS";

export const DELETE_POSITION_REQUEST = "DELETE_POSITION_REQUEST";
export const DELETE_POSITION_FAIL = "DELETE_POSITION_FAIL";
export const DELETE_POSITION_SUCCESS = "DELETE_POSITION_SUCCESS";

export const ADD_MODAL = "ADD_MODAL";
export const EDIT_MODAL = "EDIT_MODAL";
export const DELETE_MODAL = "DELETE_MODAL";
export const SET_MODAL_VALUES = "SET_MODAL_VALUES";



export const HANDLE = "HANDLE";