// PERMISSIONS
export const GET_PERMISSIONS_REQUEST = "GET_PERMISSIONS_REQUEST";
export const GET_PERMISSIONS_FAIL = "GET_PERMISSIONS_FAIL";
export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";
// TOOLS
export const GET_TOOLS_REQUEST = "GET_TOOLS_REQUEST";
export const GET_TOOLS_FAIL = "GET_TOOLS_FAIL";
export const GET_TOOLS_SUCCESS = "GET_TOOLS_SUCCESS";