export const START_REQUEST = 'START_REQUEST';
export const SET_PRICE_TYPE = 'SET_PRICE_TYPE';
export const SET_PRICE_TYPE_ERROR = 'SET_PRICE_TYPE_ERROR';
export const SET_PRICE_VALUE = 'SET_PRICE_VALUE';