export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";

export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";

export const EDIT_ITEM_REQUEST = "EDIT_ITEM_REQUEST";
export const EDIT_ITEM_FAIL = "EDIT_ITEM_FAIL";
export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";

export const ADD_MODAL = "ADD_MODAL";
export const EDIT_MODAL = "EDIT_MODAL";
export const DELETE_MODAL = "DELETE_MODAL";
export const SET_MODAL_VALUES = "SET_MODAL_VALUES";