export const GET_SUPPLIERS_REQUEST = "GET_SUPPLIERS_REQUEST";
export const GET_SUPPLIERS_FAIL = "GET_SUPPLIERS_FAIL";
export const GET_SUPPLIERS_SUCCESS = "GET_SUPPLIERS_SUCCESS";

export const GET_SUPPLIER_REQUEST = "GET_SUPPLIER_REQUEST";
export const GET_SUPPLIER_FAIL = "GET_SUPPLIER_FAIL";
export const GET_SUPPLIER_SUCCESS = "GET_SUPPLIER_SUCCESS";

export const ADD_SUPPLIER_REQUEST = "ADD_SUPPLIER_REQUEST";
export const ADD_SUPPLIER_FAIL = "ADD_SUPPLIER_FAIL";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";

export const EDIT_SUPPLIER_REQUEST = "EDIT_SUPPLIER_REQUEST";
export const EDIT_SUPPLIER_FAIL = "EDIT_SUPPLIER_FAIL";
export const EDIT_SUPPLIER_SUCCESS = "EDIT_SUPPLIER_SUCCESS";

export const DELETE_SUPPLIER_REQUEST = "DELETE_SUPPLIER_REQUEST";
export const DELETE_SUPPLIER_FAIL = "DELETE_SUPPLIER_FAIL";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";

export const GET_BANKS_REQUEST = "GET_BANKS_REQUEST";
export const GET_BANKS_FAIL = "GET_BANKS_FAIL";
export const GET_BANKS_SUCCESS = "GET_BANKS_SUCCESS";

export const GET_Currency_REQUEST = "GET_Currency_REQUEST";
export const GET_Currency_FAIL = "GET_Currency_FAIL";
export const GET_Currency_SUCCESS = "GET_Currency_SUCCESS";

export const SET_SUPPLIER_MODAL = "SET_SUPPLIER_MODAL";
export const TOGGLE_SUPPLIER_MODAL = "TOGGLE_SUPPLIER_MODAL";



/*----------------------------------------*/
export const SUPPLIERS_ADD_MODAL = 'SUPPLIERS_ADD_MODAL';
export const SUPPLIERS_OPEN_MODAL = 'SUPPLIERS_OPEN_MODAL';
export const SET_SUPPLIERS_VALUE = 'SET_SUPPLIERS_VALUE';

export const FETCH_SUPPLIER_REQUEST = "FETCH_SUPPLIER_REQUEST";
export const FETCH_SUPPLIER_FAIL = "FETCH_SUPPLIER_FAIL";
export const FETCH_SUPPLIER_SUCCESS = "FETCH_SUPPLIER_SUCCESS";