export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const GET_BARCODE_TYPES_REQUEST = "GET_BARCODE_TYPES_REQUEST";
export const GET_BARCODE_TYPES_FAIL = "GET_BARCODE_TYPES_FAIL";
export const GET_BARCODE_TYPES_SUCCESS = "GET_BARCODE_TYPES_SUCCESS";

export const ADD_BARCODE = "ADD_BARCODE";
export const DELETE_BARCODE = "DELETE_BARCODE";

export const SET_PRODUCT_MODAL = "SET_PRODUCT_MODAL";
export const TOGGLE_PRODUCT_MODAL = "TOGGLE_PRODUCT_MODAL";
export const EDITABLED_PRODCT = "EDITABLED_PRODCT";

/*----------------------------------*/
export const SET_BARCODE = 'SET_BARCODE';
export const ADD_MEASUREMENT_VALUE = 'ADD_MEASUREMENT_VALUE';
export const ADD_POINTS_VALUE = 'ADD_POINTS_VALUE';
export const ADD_UPLOAD_IMAGES = 'ADD_UPLOAD_IMAGES';
export const ADD_VALUE = 'ADD_VALUE';
export const ADD_RESULT = 'ADD_RESULT';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SELECT_GROUP = 'SELECT_GROUP';
export const SELECT_ID_IN_ARRAY = 'SELECT_ID_IN_ARRAY';
export const CLASSIFIERS_TOGGLE_MODAL = 'CLASSIFIERS_TOGGLE_MODAL';
export const CREATE_CLASSIFIERS_ERROR = 'CREATE_CLASSIFIERS_ERROR';
export const CREATE_CLASSIFIERS_SUCCESS = 'CREATE_CLASSIFIERS_SUCCESS';
export const ADD_SEARCH_TEXT = 'ADD_SEARCH_TEXT';
export const EDITABLED_PRODUCT = 'EDITABLED_PRODUCT';

export const SET_IMAGES_DATA = 'SET_IMAGES_DATA';
export const SET_PRODUCT_COLLAPSED = 'SET_PRODUCT_COLLAPSED';
export const SET_ADDED_PRODUCT = 'SET_ADDED_PRODUCT';
export const SET_DELETED_IMAGES = 'SET_DELETED_IMAGES';
export const ADD_PRODUCT_STATUS = 'ADD_PRODUCT_STATUS';

export const TOGGLE_CLASSIFIERS_STATE = 'TOGGLE_CLASSIFIERS_STATE';