export const SET_PRODUCT_VALUES = 'SET_PRODUCT_VALUES';
export const CLOSE_PRODUCT_MODAL = 'CLOSE_PRODUCT_MODAL';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const ONLY_ADD_PRODUCT = 'ONLY_ADD_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT_MODAL_VALUES = 'SET_PRODUCT_MODAL_VALUES';