export const SET_REGISTRATION_VALUES = 'SET_REGISTRATION_VALUES';
export const REGISTRATION_REQUEST_ERROR = 'REGISTRATION_REQUEST_ERROR';
export const REGISTRATION_REQUEST_SUCCESS = 'REGISTRATION_REQUEST_SUCCESS';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_ERROR = 'VERIFY_ERROR';