export const GET_GROUPS_REQUEST = "GET_GROUPS_REQUEST";
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";

export const GET_GROUP_REQUEST = "GET_GROUP_REQUEST";
export const GET_GROUP_FAIL = "GET_GROUP_FAIL";
export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS";

export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST";
export const ADD_GROUP_FAIL = "ADD_GROUP_FAIL";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";

export const EDIT_GROUP_REQUEST = "EDIT_GROUP_REQUEST";
export const EDIT_GROUP_FAIL = "EDIT_GROUP_FAIL";
export const EDIT_GROUP_SUCCESS = "EDIT_GROUP_SUCCESS";

export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
export const DELETE_GROUP_FAIL = "DELETE_GROUP_FAIL";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";

export const GET_SUB_GROUPS_REQUEST = "GET_SUB_GROUPS_REQUEST";
export const GET_SUB_GROUPS_FAIL = "GET_SUB_GROUPS_FAIL";
export const GET_SUB_GROUPS_SUCCESS = "GET_SUB_GROUPS_SUCCESS";


export const GET_SUB_GROUP_REQUEST = "GET_SUB_GROUP_REQUEST";
export const GET_SUB_GROUP_FAIL = "GET_SUB_GROUP_FAIL";
export const GET_SUB_GROUP_SUCCESS = "GET_SUB_GROUP_SUCCESS";

export const ADD_SUB_GROUP_REQUEST = "ADD_SUB_GROUP_REQUEST";
export const ADD_SUB_GROUP_FAIL = "ADD_SUB_GROUP_FAIL";
export const ADD_SUB_GROUP_SUCCESS = "ADD_SUB_GROUP_SUCCESS";

export const EDIT_SUB_GROUP_REQUEST = "EDIT_SUB_GROUP_REQUEST";
export const EDIT_SUB_GROUP_FAIL = "EDIT_SUB_GROUP_FAIL";
export const EDIT_SUB_GROUP_SUCCESS = "EDIT_SUB_GROUP_SUCCESS";

export const DELETE_SUB_GROUP_REQUEST = "DELETE_SUB_GROUP_REQUEST";
export const DELETE_SUB_GROUP_FAIL = "DELETE_SUB_GROUP_FAIL";
export const DELETE_SUB_GROUP_SUCCESS = "DELETE_SUB_GROUP_SUCCESS";


export const SET_GROUP_MODAL = "SET_GROUP_MODAL";
export const TOGGLE_GROUP_MODAL = "TOGGLE_GROUP_MODAL";
export const TOGGLE_SUB_GROUP_MODAL  = "TOGGLE_SUB_GROUP_MODAL";
export const OPEN_MENU = "OPEN_MENU";
export const SELECT_GROUP = "SELECT_GROUP";

export const SELECT_GROUPS_REQUEST = 'SELECT_GROUPS_REQUEST';
export const SELECT_GROUPS_FAIL = 'SELECT_GROUPS_FAIL';
export const SELECT_GROUPS_SUCCESS = 'SELECT_GROUPS_SUCCESS';

export const SET_TOGGLE_SUB_MODAL_VALUE = 'SET_TOGGLE_SUB_MODAL_VALUE';
export const SET_SUB_MODAL_NAME_VALUE = 'SET_SUB_MODAL_NAME_VALUE';

export const TOGGLE_SUB_MODAL = 'TOGGLE_SUB_MODAL';

export const START_MOVING_GROUP = 'START_MOVING_GROUP';
export const END_MOVING_GROUP = 'END_MOVING_GROUP';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_ALT_SEARCH_VALUE = 'SET_ALT_SEARCH_VALUE';
export const SHOW_ALTERNATIVE = 'SHOW_ALTERNATIVE';

/*
*       For products
* */

export const SET_PRODUCT_GROUPS = 'SET_PRODUCT_GROUPS';