export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGOUT_REQUEST_FAIL = "LOGOUT_REQUEST_FAIL";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const LOGIN_EMPTY = 'LOGIN_EMPTY';
export const PASSWORD_EMPTY = 'PASSWORD_EMPTY';

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const RESET_PAGE = 'RESET_PAGE';