export const SET_BARCODE_VALUE = 'SET_BARCODE_VALUE';
export const SET_BARCODE = 'SET_BARCODE';
export const SET_DELETE_BARCODE = 'SET_DELETE_BARCODE';
export const SET_PRODUCTS_BARCODE_VALUE = 'SET_PRODUCTS_BARCODE_VALUE';
export const SET_CLEAN_VALUE = 'SET_CLEAN_VALUE';
export const SET_AND_CLOSE = 'SET_AND_CLOSE';