export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const CHANGE_PROGRESS_STATUS = 'CHANGE_PROGRESS_STATUS';
export const SEND_RESET_PASSWORD_MAIL_ERROR = 'SEND_RESET_PASSWORD_MAIL_ERROR';
export const SEND_RESET_PASSWORD_MAIL_SUCCESS = 'SEND_RESET_PASSWORD_MAIL_SUCCESS';