export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const ADD_USER_REQUEST = "ADD_USERS_REQUEST";
export const ADD_USER_FAIL = "ADD_USERS_FAIL";
export const ADD_USER_SUCCESS = "ADD_USERS_SUCCESS";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const ADD_MODAL = "ADD_MODAL";
export const EDIT_MODAL = "EDIT_MODAL";
export const DELETE_MODAL = "DELETE_MODAL";
export const SET_MODAL_VALUES = "SET_MODAL_VALUES";