export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const SET_USER_MODAL = "SET_USER_MODAL";
export const TOGGLE_USER_MODAL = "TOGGLE_USER_MODAL";

export const TOGGLE_EDITABLE_USER = 'TOGGLE_EDITABLE_USER';