// GET MENU
export const GET_MENU_REQUEST = 'GET_MENU_REQUEST';
export const GET_MENU_FAIL = 'GET_MENU_FAIL';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
// GET MENU ITE<
export const GET_MENU_ITEM_REQUEST = 'GET_MENU_ITEM_REQUEST';
export const GET_MENU_ITEM_FAIL = 'GET_MENU_ITEM_FAIL';
export const GET_MENU_ITEM_SUCCESS = 'GET_MENU_ITEM_SUCCESS';
// ADD MENU
export const ADD_MENU_REQUEST = 'ADD_MENU_REQUEST';
export const ADD_MENU_FAIL = 'ADD_MENU_FAIL';
export const ADD_MENU_SUCCESS = 'ADD_MENU_SUCCESS';

// EDIT MENU
export const EDIT_MENU_REQUEST = 'EDIT_MENU_REQUEST';
export const EDIT_MENU_FAIL = 'EDIT_MENU_FAIL';
export const EDIT_MENU_SUCCESS = 'EDIT_MENU_SUCCESS';

// DELETE MENU
export const DELETE_MENU_REQUEST = 'DELETE_MENU_REQUEST';
export const DELETE_MENU_FAIL = 'DELETE_MENU_FAIL';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';

// MODAL
export const TOGGLE_MENU_MODAL = 'TOGGLE_MENU_MODAL';
export const SET_MENU_MODAL = 'SET_MENU_MODAL';