export function selectedsF(heightLen, header, len){
   return {A: {
      1: {
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"4 !important",
        fontFamily: "Arial",
        fontSize: "26px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      2: {
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"4 !important",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-7]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"4 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-6]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-3]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-2]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-8]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-4]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
    },
    G:{
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      // 2: {
      //   alignItems: "center",
      //   backgroundColor: "undefined !important",
      //   color: "undefined !important",
      //   display: "flex",
      //   zIndex:"2 !important",
      //   fontFamily: "Arial",
      //   fontSize: "20px",
      //   fontStyle: "normal",
      //   fontWeight: "bold",
      //   justifyContent: "center",
      //   textDecoration: "none",
      //   border:"1px solid black",
      // },
    },
    "F":{
      2:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"4 !important",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
    },
    B:{
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-7]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-6]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-3]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-2]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        zIndex:"2 !important",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
    }
  }
}

  

  export function defExpandedsF(heightLen, len){
      return [ 
    {
      row: 1,
      col: "A",
      colSize: 11,
      rowSize: 1,
    },
    {
      row: 2,
      col: "A",
      colSize: 4,
      rowSize: 1,
    },
    {
      row: 3,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 4,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 5,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 6,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 7,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: heightLen-8,
      col: "A",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: heightLen-4,
      col: "A",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: heightLen-7,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: heightLen-6,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: heightLen-3,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: heightLen-2,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: 2,
      col: "F" ,
      colSize: 4,
      rowSize: 1,
    },
    // {
    //   row: 2,
    //   col: "G",
    //   colSize: 3,
    //   rowSize: 1,
    // },
    {
      row: 3,
      col: "G",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 4,
      col: "G",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 5,
      col: "G",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 6,
      col: "G",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 7,
      col: "G",
      colSize: 3,
      rowSize: 1,
    },
  ]
}