export function selectedsF(heightLen, header, len){
   return {A: {
      1: {
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "26px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      2: {
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-7]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-6]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-3]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-2]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-8]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-4]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
    },
    [header]:{
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      2: {
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
    },
    [String.fromCharCode(65+len-4) ]:{
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
    },
    B:{
      3:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      4:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      5:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      6:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      7:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-7]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-6]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-3]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
      [heightLen-2]:{
        alignItems: "center",
        backgroundColor: "undefined !important",
        color: "undefined !important",
        display: "flex",
        fontFamily: "Arial",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        justifyContent: "center",
        textDecoration: "none",
        border:"1px solid black",
      },
    }
  }
}

  

  export function defExpandedsF(heightLen, len){
      return [ 
    {
      row: 1,
      col: "A",
      colSize: len,
      rowSize: 1,
    },
    {
      row: 2,
      col: "A",
      colSize: 4,
      rowSize: 1,
    },
    {
      row: 2,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 3,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 4,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 5,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 6,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 7,
      col: "B",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: heightLen-8,
      col: "A",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: heightLen-4,
      col: "A",
      colSize: 3,
      rowSize: 1,
    },
    {
      row: heightLen-7,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: heightLen-6,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: heightLen-3,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: heightLen-2,
      col: "B",
      colSize: 2,
      rowSize: 1,
    },
    {
      row: 2,
      col: String.fromCharCode(65+len-5) ,
      colSize: 4,
      rowSize: 1,
    },
    {
      row: 2,
      col: String.fromCharCode(65+len-4),
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 3,
      col: String.fromCharCode(65+len-4),
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 4,
      col: String.fromCharCode(65+len-4),
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 5,
      col: String.fromCharCode(65+len-4),
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 6,
      col: String.fromCharCode(65+len-4),
      colSize: 3,
      rowSize: 1,
    },
    {
      row: 7,
      col: String.fromCharCode(65+len-4),
      colSize: 3,
      rowSize: 1,
    },
  ]
}