export const SET_VALUES = 'SET_VALUES';
export const SET_RECOVER_DATA = 'SET_RECOVER_DATA';
export const SET_ERROR_DATA = 'SET_ERROR_DATA';
export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const CHANGE_PROGRESS_STATUS = 'CHANGE_PROGRESS_STATUS';
export const SEND_RESET_PASSWORD_MAIL_SUCCESS = 'SEND_RESET_PASSWORD_MAIL_SUCCESS';
export const SEND_RESET_PASSWORD_MAIL_ERROR = 'SEND_RESET_PASSWORD_MAIL_ERROR';